sudo: required
services:
    - docker

before_install:
    - docker build -t k123cee/multi-client-test -f ./client/Dockerfile.dev ./client/


script:
    - docker run -e CI=true k123cee/multi-client-test npm test


after_success:
    - docker build -t k123cee/multi-client ./client
    - docker build -t k123cee/multi-nginx ./nginx
    - docker build -t k123cee/multi-server ./server
    - docker build -t k123cee/multi-worker ./worker
